Fixed erb file to correctly call custom functions.
This fixes the following error message in Puppet 3.1:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template puppet-icinga/common/etc/icinga/htpasswd.users.erb:
  Filepath: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/functions.rb
  Line: 149
  Detail: custom functions must be called with a single array that contains the arguments. For example, function_example([1]) instead of function_example(1) at /etc/puppetlabs/puppet/environments/production/modules/puppet-icinga/manifests/master.pp:47 on node your_node_name_here
  Warning: Not using cache on failed catalog
  Error: Could not retrieve catalog; skipping run